In [8]:
from fastai.vision.all import *
import PIL.Image

In [18]:
# Open an image
i1 = PIL.Image.open("/home/vinayak/Desktop/i1.png").convert('RGB')

In [29]:
# Accessing weights (and biases) of conv layer
c1 = nn.Conv2d(3, 10, (5, 5)).state_dict()['weight']

In [30]:
# How does it look, a convolutional kernel
c1.shape

torch.Size([10, 3, 5, 5])

In [35]:
# One kernel in particular
c1[1, :, :, :]

tensor([[[ 0.0675, -0.0509, -0.1092, -0.0358, -0.0899],
         [-0.0134,  0.0515, -0.0097,  0.0579,  0.0372],
         [-0.0673,  0.0036,  0.0859,  0.0949, -0.0306],
         [-0.0823, -0.0032, -0.0080,  0.0595,  0.0859],
         [ 0.0845, -0.1106,  0.0994,  0.0659,  0.0292]],

        [[ 0.0514, -0.0926, -0.0267, -0.0503, -0.0511],
         [-0.0931, -0.0029, -0.0372, -0.0895,  0.0335],
         [-0.0738,  0.1122,  0.0498,  0.0635,  0.0117],
         [ 0.0848,  0.0630, -0.0796,  0.0632,  0.1114],
         [-0.0783,  0.1146,  0.0294, -0.0692,  0.0724]],

        [[ 0.0144, -0.0462, -0.0410, -0.0291, -0.0703],
         [ 0.0103,  0.0266,  0.0124,  0.0005, -0.0975],
         [ 0.0575, -0.0175, -0.0805,  0.0050, -0.0864],
         [-0.0722, -0.1129, -0.0620,  0.0307, -0.0310],
         [-0.0976, -0.0207,  0.0244, -0.0306, -0.0169]]])

In [43]:
# Default image tensor shape
tensor(i1).shape

torch.Size([649, 768, 3])

In [80]:
# NCHW format
# Convert image to tensor
# Add axis in 0th postition
# Swap the last channel and 0th position axes
# Drop the unwanted swapped last axis
# Unsqueeze the axis on the 0th position for batch dimension
b1 = tensor(i1).\
     unsqueeze(0).\
     transpose(0, -1).\
     squeeze(-1).\
     unsqueeze(0).\
     float()

In [83]:
b1.shape

torch.Size([1, 3, 649, 768])

In [81]:
k1 = c1[1, :, :, :]

In [82]:
k1.shape

torch.Size([3, 5, 5])

In [115]:
p = F.conv2d(b1, weight = k1.unsqueeze(0))
p.shape

torch.Size([1, 1, 645, 764])

In [110]:
# 0th kernel across 0th position
m1 = F.conv2d(b1[:, 0, :, :].unsqueeze(1), k1[0].unsqueeze(0).unsqueeze(0))

In [111]:
# 1st kernel across the 1st channel
m2 = F.conv2d(b1[:, 1, :, :].unsqueeze(1), k1[1].unsqueeze(0).unsqueeze(0))

In [112]:
# 2nd kernel across 2nd position
m3 = F.conv2d(b1[:, 2, :, :].unsqueeze(1), k1[2].unsqueeze(0).unsqueeze(0))

In [117]:
(m1 + m2 + m3)

tensor([[[[-102.4522, -102.4522, -102.4522,  ..., -102.4522, -102.4522,
           -102.4522],
          [-102.4522, -102.4522, -102.4522,  ..., -102.4522, -102.4522,
           -102.4522],
          [-102.4522, -102.4522, -102.4522,  ..., -102.4522, -102.4522,
           -102.4522],
          ...,
          [-102.4522, -102.4522, -102.4522,  ..., -102.4522, -102.4522,
           -102.4522],
          [-102.4522, -102.4522, -102.4522,  ..., -102.4522, -102.4522,
           -102.4522],
          [-102.4522, -102.4522, -102.4522,  ..., -102.4522, -102.4522,
           -102.4522]]]])

In [116]:
p

tensor([[[[-102.4523, -102.4523, -102.4523,  ..., -102.4523, -102.4523,
           -102.4523],
          [-102.4523, -102.4523, -102.4523,  ..., -102.4523, -102.4523,
           -102.4523],
          [-102.4523, -102.4523, -102.4523,  ..., -102.4523, -102.4523,
           -102.4523],
          ...,
          [-102.4523, -102.4523, -102.4523,  ..., -102.4523, -102.4523,
           -102.4523],
          [-102.4523, -102.4523, -102.4523,  ..., -102.4523, -102.4523,
           -102.4523],
          [-102.4523, -102.4523, -102.4523,  ..., -102.4523, -102.4523,
           -102.4523]]]])

In [121]:
r = resnet18()
r

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [125]:
r.conv1.state_dict()["weight"].shape

torch.Size([64, 3, 7, 7])

In [127]:
r.conv1.state_dict()["weight"][0, :, :, :]

tensor([[[ 0.0132,  0.0225,  0.0156,  0.0134, -0.0798, -0.0179,  0.0099],
         [-0.0246,  0.0104,  0.0133, -0.0083, -0.0063, -0.0047, -0.0138],
         [-0.0100,  0.0117, -0.0221,  0.0495, -0.0066,  0.0348, -0.0357],
         [ 0.0227,  0.0227,  0.0319, -0.0081, -0.0353, -0.0204, -0.0070],
         [ 0.0559,  0.0416, -0.0362, -0.0068,  0.0162,  0.0341,  0.0243],
         [-0.0244,  0.0027, -0.0644, -0.0403,  0.0371, -0.0118,  0.0355],
         [ 0.0390,  0.0308, -0.0239, -0.0263,  0.0377,  0.0097,  0.0148]],

        [[ 0.0072,  0.0077, -0.0126,  0.0213, -0.0059,  0.0057,  0.0107],
         [ 0.0580,  0.0121,  0.0336, -0.0508, -0.0073,  0.0149, -0.0018],
         [-0.0106,  0.0351, -0.0121,  0.0151, -0.0207, -0.0151, -0.0175],
         [ 0.0238,  0.0175,  0.0049, -0.0130,  0.0229, -0.0026,  0.0412],
         [-0.0224, -0.0172, -0.0011,  0.0390,  0.0310, -0.0087, -0.0072],
         [ 0.0275,  0.0072,  0.0149,  0.0123, -0.0177, -0.0111, -0.0377],
         [ 0.0168,  0.0043,  0.0250,