In [2]:
from fastai.vision.all import *

In [3]:
resnet50()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [8]:
doc(ConvLayer)

In [9]:
c1 = ConvLayer(3, 10, stride = 2)
c1

ConvLayer(
  (0): Conv2d(3, 10, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
  (1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
)

In [10]:
c2 = ConvLayer(3, 10, stride = 2, norm_type = NormType.BatchZero)
c2

ConvLayer(
  (0): Conv2d(3, 10, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
  (1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
)

In [16]:
ip = torch.randn(16, 3, 4, 4)

In [18]:
c1(ip)

tensor([[[[1.1818, 0.0000],
          [1.5136, 0.0000]],

         [[0.0000, 0.5633],
          [0.0000, 0.0000]],

         [[0.4988, 1.4803],
          [0.0000, 0.2291]],

         [[0.3766, 0.0699],
          [1.2679, 0.1402]],

         [[0.0000, 0.6582],
          [0.7351, 1.9943]],

         [[0.0000, 0.0000],
          [0.0000, 0.6260]],

         [[0.0000, 0.9503],
          [0.0000, 2.5744]],

         [[0.0000, 0.0000],
          [0.2188, 0.7357]],

         [[0.0000, 2.5106],
          [0.0000, 0.5666]],

         [[0.0000, 0.1822],
          [1.1990, 0.0000]]],


        [[[0.9573, 0.1281],
          [0.0000, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 1.0450]],

         [[0.0000, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 0.2380],
          [1.0606, 0.0000]],

         [[0.5887, 0.0926],
          [1.3440, 0.6625]],

         [[0.0000, 0.6691],
          [0.0000, 0.2913]],

         [[0.0000, 0.0000],
          [0.6817, 0.0000]],

         [[0

In [22]:
c2[0](ip)

tensor([[[[-1.0914e+00,  2.1288e+00],
          [-8.1309e-01,  4.6251e-01]],

         [[-1.7071e+00, -6.1692e-01],
          [-9.3272e-01,  2.3487e+00]],

         [[-3.4947e-01, -6.5682e-01],
          [-1.3410e+00, -1.4342e+00]],

         [[ 1.6700e+00,  2.2862e-01],
          [-2.0649e+00, -3.1967e-01]],

         [[ 8.2776e-01,  3.7419e-01],
          [-4.5400e-02, -1.9956e-01]],

         [[-8.1729e-02, -1.2265e+00],
          [ 7.6439e-02, -7.0828e-01]],

         [[-2.7207e-01,  1.4991e+00],
          [ 2.5820e-01,  4.6852e-02]],

         [[ 8.3622e-02, -1.3328e+00],
          [ 4.4947e-01,  1.3075e+00]],

         [[ 1.3285e-01, -3.1901e-02],
          [-1.8914e+00, -4.3054e-01]],

         [[ 1.2504e+00,  2.4814e-01],
          [-6.3304e-01,  7.2177e-01]]],


        [[[ 2.4124e-01, -1.1629e+00],
          [-6.3116e-01,  1.6266e+00]],

         [[-4.2184e-01, -1.2065e+00],
          [-9.3387e-01,  2.9780e+00]],

         [[-4.1511e-01, -6.6756e-01],
          [-4.2797e-01, 

In [35]:
list(nn.BatchNorm2d(10).parameters())

[Parameter containing:
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)]

In [28]:
list(c1[1].parameters())

[Parameter containing:
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True),
 Parameter containing:
 tensor([0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010,
         0.0010], requires_grad=True)]

In [27]:
list(c2[1].parameters())

[Parameter containing:
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True),
 Parameter containing:
 tensor([0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010,
         0.0010], requires_grad=True)]